### ISSUE TITLE
多个then 的错误信息,结果只是最后一个then的错误信息吗,怎么在第一个then错误时就返回

### ISSUE THREAD

**Issue by jutbin** [shengyanli1982/vowlink#9]
package main

import (
	"fmt"

	vl "github.com/shengyanli1982/vowlink"
)

func main() {

	var val int

	a := 101

	rt := vl.NewPromise(func(resolve func(interface{}), reject func(error)) {

		if a < 100 {
			fmt.Println("小于100")
			a--
			resolve(a)
		}
		reject(fmt.Errorf("rejected.100"))

	}).Then(func(value interface{}) interface{} {
		if a < 90 {
			fmt.Println("小于90")
			val = value.(int) - 1
		}
		return val

	}, func(error) error {
		// 如果 promise 被拒绝，我们将返回一个新的错误信息 "rejected."
		// If the promise is rejected, we return a new error message "rejected."
		fmt.Println("1小于90")
		return fmt.Errorf("rejected.90")
	}).Then(func(value interface{}) interface{} {
		if a < 80 {
			fmt.Println("小于80")
			val = value.(int) - 1
		}
		return val

	}, func(error) error {
		// 如果 promise 被拒绝，我们将返回一个新的错误信息 "rejected."
		// If the promise is rejected, we return a new error message "rejected."
		fmt.Println("1小于80")
		return fmt.Errorf("rejected.80")
	}).Then(func(value interface{}) interface{} {
		if a < 70 {
			fmt.Println("小于70")
			val = value.(int) - 1
		}
		return val

	}, func(error) error {
		fmt.Println("1小于70")
		// 如果 promise 被拒绝，我们将返回一个新的错误信息 "rejected."
		// If the promise is rejected, we return a new error message "rejected."
		return fmt.Errorf("rejected.7000")
	})

	if rt.GetReason() != nil {
		fmt.Println(rt.GetReason().Error())
	} else {

		fmt.Println(rt.GetValue())
	}

}

**Comment by jutbin** [comment]
我期望输出的时rejected.90  但是实际确是rejected.7000  这是为什么呢

**Comment by shengyanli1982** [comment]
非常感谢你的支持，看到你这边的 demo 代码了。 我觉得处理过程没有问题。 因为在 Promise 的 then() 的第二参数所执行的函数和 catch() 都是对上一次 Promise 中 error 的一个捕获和处理。函数的主要作用是提供一种方式来响应和处理 Promise 失败的情况。你可以认为它是一种错误处理或异常捕获的机制。

说到你的代码中，因为你在 then() 的第二参数的函数中调用 return fmt.Errorf ，实际在创建新的错误，当然需要后续的 catch() 或者 then() 第二参数函数执行捕获。 即便你在 then() 的第二参数的函数中 return err （返回原有错误）也一样。 除非你 return nil。表示你已经完成处理了函数，并认为 Promise 的状态可以恢复了，那么后续的 then()  和 catch() 将继续执行。

不过还是非常感谢你，你的代码让我发现我这边几个处理的 bug，这个需要破坏性的更新，这个是我非常不愿意看到的。但是没有办法，必须修复，要不然 vowlink 没有办法真正意义上的工作。

新的功能，你可以参考下 examples 目录下的 case9 - case12 这几个用例，这几个全新的。 你也看看测试文件中新的测试用例。

欢迎你继续试用与反馈。
